/-
Top-level import surface for the project.

The concrete `Concrete*` modules are the active first-principles foundation.
The paper-facing theorem modules remain imported for their canonical wrapper
names, and those modules now terminate directly at the concrete stack.
-/

import SemanticConvergence.Foundations
import SemanticConvergence.ConcreteCore
import SemanticConvergence.ConcretePrior
import SemanticConvergence.ConcreteHierarchy
import SemanticConvergence.ConcreteFunctional
import SemanticConvergence.ConcreteBelief
import SemanticConvergence.ConcreteSemantic
import SemanticConvergence.ConcretePosteriorDecay
import SemanticConvergence.ConcreteRates
import SemanticConvergence.ConcreteProbabilisticConvergence
import SemanticConvergence.ConcreteSubstrateBridge
import SemanticConvergence.ConcreteNoise
import SemanticConvergence.ConcreteSelfReference
import SemanticConvergence.ConcreteBoundary
import SemanticConvergence.ConcreteSurrogate
import SemanticConvergence.HellingerContraction
import SemanticConvergence.Hierarchy
import SemanticConvergence.Functional
import SemanticConvergence.DiscreteConvexDuality
import SemanticConvergence.KLInstance
import SemanticConvergence.CompactKernel
import SemanticConvergence.MartingaleContraction
import SemanticConvergence.Belief
import SemanticConvergence.Semantic
import SemanticConvergence.Noise
import SemanticConvergence.Rates
import SemanticConvergence.SelfReference
import SemanticConvergence.Boundary
import SemanticConvergence.Surrogate
import SemanticConvergence.Ontology
import SemanticConvergence.Manifest
